# Generated by Django 4.2.15 on 2024-08-31 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataStudentScore',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('deleted', models.BooleanField(default=False, help_text='是否删除')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('edu_commission_id', models.BigIntegerField()),
                ('grade_type', models.CharField(blank=True, max_length=10, null=True)),
                ('school_id', models.BigIntegerField()),
                ('base_grade_id', models.BigIntegerField()),
                ('grade_id', models.BigIntegerField()),
                ('class_id', models.BigIntegerField()),
                ('student_ID', models.CharField(blank=True, max_length=20, null=True)),
                ('plan_id', models.BigIntegerField()),
                ('project_id', models.BigIntegerField()),
                ('projectNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=2, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('year', models.CharField(blank=True, max_length=20, null=True)),
                ('grade_name', models.CharField(blank=True, max_length=20, null=True)),
                ('class_name', models.CharField(blank=True, max_length=20, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('device_number', models.CharField(blank=True, max_length=200, null=True)),
                ('achievement', models.CharField(blank=True, max_length=20, null=True)),
                ('achievement_int', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('score', models.DecimalField(decimal_places=0, max_digits=20)),
                ('score_grade', models.CharField(blank=True, max_length=20, null=True)),
                ('score_weight', models.DecimalField(decimal_places=2, max_digits=20)),
                ('height', models.DecimalField(decimal_places=1, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=10)),
                ('remark', models.CharField(blank=True, max_length=999, null=True)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'data_student_score',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('deleted', models.BooleanField(default=False, help_text='是否删除')),
                ('full_filename', models.CharField(help_text='文件全名', max_length=255)),
                ('filename', models.CharField(help_text='文件名', max_length=255)),
                ('extension', models.CharField(help_text='文件后缀', max_length=16)),
                ('md5', models.CharField(help_text='文件md5值', max_length=64)),
                ('path', models.CharField(help_text='文件相对路径', max_length=512)),
                ('size', models.BigIntegerField()),
                ('file_type', models.PositiveSmallIntegerField(choices=[(0, '默认'), (1, '系统'), (2, '用户上传')], default=2, help_text='文件类型')),
            ],
            options={
                'verbose_name': '文件信息',
                'verbose_name_plural': '文件信息',
                'db_table': 'file_info',
            },
        ),
    ]
