# Generated by Django 4.2.15 on 2024-08-31 06:34

import common.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('deleted', models.BooleanField(default=False, help_text='是否删除')),
                ('name', models.CharField(default='', help_text='节点名称', max_length=255)),
                ('parent', common.fields.SimpleForeignKey(blank=True, db_constraint=False, help_text='父节点', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auths.department')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('deleted', models.BooleanField(default=False, help_text='是否删除')),
                ('name', models.CharField(default='', help_text='角色名称', max_length=32)),
                ('description', models.CharField(default='', help_text='角色名称', max_length=32)),
            ],
            options={
                'verbose_name': '角色信息',
                'verbose_name_plural': '角色信息',
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('deleted', models.BooleanField(default=False, help_text='是否删除')),
                ('nickname', models.CharField(blank=True, default='', help_text='账号名', max_length=64, null=True)),
                ('account', models.CharField(default=None, help_text='账号ID', max_length=10)),
                ('phone', models.CharField(blank=True, default='', help_text='手机号', max_length=11)),
                ('email', models.CharField(blank=True, default='', help_text='邮箱', max_length=32)),
                ('avatar', common.fields.FileIdField(blank=True, default='', help_text='头像', max_length=255)),
                ('password', models.CharField(default='', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, default=None, help_text='最近登录时间', null=True)),
                ('enable', models.BooleanField(default=True, help_text='是否启用')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('deleted', models.BooleanField(default=False, help_text='是否删除')),
                ('role', common.fields.SimpleForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_role', to='auths.role')),
                ('user', common.fields.SimpleForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='role_user', to='auths.user')),
            ],
            options={
                'verbose_name': '用户角色',
                'verbose_name_plural': '用户角色',
                'db_table': 'user_role',
            },
        ),
        migrations.CreateModel(
            name='UserDepartment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('deleted', models.BooleanField(default=False, help_text='是否删除')),
                ('department', common.fields.SimpleForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_department', to='auths.department')),
                ('user', common.fields.SimpleForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='department_user', to='auths.user')),
            ],
            options={
                'verbose_name': '用户部门',
                'verbose_name_plural': '用户部门',
                'db_table': 'user_department',
            },
        ),
    ]
