# Generated by Django 4.2.15 on 2024-09-03 14:14

import common.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, help_text="创建时间"),
                ),
                ("update_time", models.DateTimeField(auto_now=True, help_text="更新时间")),
                ("deleted", models.BooleanField(default=False, help_text="是否删除")),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "任务分类",
                "verbose_name_plural": "任务分类",
                "db_table": "task_category",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, help_text="创建时间"),
                ),
                ("update_time", models.DateTimeField(auto_now=True, help_text="更新时间")),
                ("deleted", models.BooleanField(default=False, help_text="是否删除")),
                (
                    "nickname",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="账号名",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "account",
                    models.CharField(default=None, help_text="账号ID", max_length=10),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", help_text="手机号", max_length=11
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, default="", help_text="邮箱", max_length=32
                    ),
                ),
                (
                    "avatar",
                    common.fields.FileIdField(
                        blank=True, default="", help_text="头像", max_length=255
                    ),
                ),
                ("password", models.CharField(default="", max_length=128)),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, default=None, help_text="最近登录时间", null=True
                    ),
                ),
                ("enable", models.BooleanField(default=True, help_text="是否启用")),
            ],
            options={
                "verbose_name": "用户信息",
                "verbose_name_plural": "用户信息",
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, help_text="创建时间"),
                ),
                ("update_time", models.DateTimeField(auto_now=True, help_text="更新时间")),
                ("deleted", models.BooleanField(default=False, help_text="是否删除")),
                ("title", models.CharField(default="未命名的任务2024-09-03", max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("completed", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="auths.taskcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户任务",
                "verbose_name_plural": "用户任务",
                "db_table": "task",
            },
        ),
    ]
