"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
from .base_settings import *
from pathlib import Path

DEBUG = True

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
        'HOST': 'localhost',
        'USER': 'root',
        'PASSWORD': '123',  # same as root
        'NAME': 'pdca',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8',
        },
    },
}

FILE_CDN_DOMAIN = ''


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
        },
    },
}

FILE_PATH = '/opt/testing-mgt-ljqc/files'
# FILE_PATH = '/Users/jiaochanghao/LJQC/file''
