
[uwsgi]
http=:80
env = IS_DEBUG=0
chdir=/Users/jiaochanghao/gitee_clone/django-rest-framework1/api
module=api.wsgi:application
master=True
processes=16
harakiri=1800
pidfile=/Users/jiaochanghao/gitee_clone/django-rest-framework1/api/conf/uwsgi.pid
vacuum=True
max-requests=10000
max-requests-delta=100
#enable-threads=True
virtualenv = /Users/jiaochanghao/.virtualenvs/api
daemonize=/Users/jiaochanghao/gitee_clone/django-rest-framework1/api/logs/uwsgi.log
log-maxsize=104857600
reload-on-rss=240
reload-mercy=180
max-worker-lifetime=3600
post-buffering=262144
post-buffering-bufsize=262144
#gevent=1000
stats=/Users/jiaochanghao/gitee_clone/django-rest-framework1/api/conf/uwsgi_stat.sock
