# Generated by Django 3.2.10 on 2023-07-28 19:32

import common.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('deleted', models.BooleanField(default=False, help_text='是否删除')),
                ('name', models.CharField(default='', help_text='资源url', max_length=64)),
                ('description', models.CharField(default='', help_text='资源描述', max_length=128)),
                ('icon', models.CharField(default='', help_text='图标', max_length=64)),
                ('tree_level', models.IntegerField(default=0, help_text='树')),
            ],
            options={
                'verbose_name': '资源',
                'verbose_name_plural': '资源',
                'db_table': 'resources',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('deleted', models.BooleanField(default=False, help_text='是否删除')),
                ('name', models.CharField(default='', help_text='角色名称', max_length=32)),
                ('description', models.CharField(default='', help_text='角色名称', max_length=32)),
            ],
            options={
                'verbose_name': '角色信息',
                'verbose_name_plural': '角色信息',
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('deleted', models.BooleanField(default=False, help_text='是否删除')),
                ('account', models.CharField(default=None, help_text='账号', max_length=11)),
                ('username', models.CharField(default='', help_text='姓名', max_length=32)),
                ('mobile', models.CharField(blank=True, default='', help_text='联系电话', max_length=32)),
                ('email', models.CharField(blank=True, default='', help_text='邮件', max_length=32)),
                ('avatar', common.fields.FileIdField(blank=True, default='', help_text='头像', max_length=255)),
                ('password', models.CharField(default='', max_length=128)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, default=None, help_text='最近登录时间', null=True)),
                ('expire_time', models.DateTimeField(blank=True, default=None, help_text='账号过期时间', null=True)),
                ('enable', models.BooleanField(default=True, help_text='是否启用')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='WxUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('deleted', models.BooleanField(default=False, help_text='是否删除')),
                ('mobile', models.CharField(default='', help_text='手机号', max_length=32)),
                ('account', models.CharField(default='', help_text='账号', max_length=32)),
                ('password', models.CharField(default='', help_text='密码', max_length=255)),
                ('openid', models.CharField(default='', help_text='姓名', max_length=255)),
            ],
            options={
                'verbose_name': '微信用户信息',
                'verbose_name_plural': '微信用户信息',
                'db_table': 'wx_user',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('deleted', models.BooleanField(default=False, help_text='是否删除')),
                ('role', common.fields.SimpleForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_role', to='auths.role')),
                ('user', common.fields.SimpleForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='role_user', to='auths.user')),
            ],
            options={
                'verbose_name': '用户角色',
                'verbose_name_plural': '用户角色',
                'db_table': 'user_role',
            },
        ),
        migrations.CreateModel(
            name='RoleResources',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('deleted', models.BooleanField(default=False, help_text='是否删除')),
                ('resources', common.fields.SimpleForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='role_resources', to='auths.resources')),
                ('role', common.fields.SimpleForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resources_role', to='auths.role')),
            ],
            options={
                'verbose_name': '角色资源',
                'verbose_name_plural': '角色资源',
                'db_table': 'role_resources',
            },
        ),
    ]
