# Generated by Django 3.2.10 on 2024-01-01 06:38

import common.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('deleted', models.BooleanField(default=False, help_text='是否删除')),
                ('name', models.CharField(default='', help_text='节点名称', max_length=255)),
                ('parent', common.fields.SimpleForeignKey(blank=True, db_constraint=False, help_text='父节点', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auths.department')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='UserDepartment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('deleted', models.BooleanField(default=False, help_text='是否删除')),
                ('department', common.fields.SimpleForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_department', to='auths.department')),
                ('user', common.fields.SimpleForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='department_user', to='auths.user')),
            ],
            options={
                'verbose_name': '用户部门',
                'verbose_name_plural': '用户部门',
                'db_table': 'user_department',
            },
        ),
        migrations.RemoveField(
            model_name='roleresources',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='roleresources',
            name='role',
        ),
        migrations.DeleteModel(
            name='WxUser',
        ),
        migrations.DeleteModel(
            name='Resources',
        ),
        migrations.DeleteModel(
            name='RoleResources',
        ),
    ]
