# Generated by Django 3.2.10 on 2024-01-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_auto_20240101_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, default='', help_text='姓名', max_length=32, null=True),
        ),
    ]
