# Generated by Django 3.2.10 on 2023-07-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('deleted', models.BooleanField(default=False, help_text='是否删除')),
                ('full_filename', models.CharField(help_text='文件全名', max_length=255)),
                ('filename', models.CharField(help_text='文件名', max_length=255)),
                ('extension', models.CharField(help_text='文件后缀', max_length=16)),
                ('md5', models.CharField(help_text='文件md5值', max_length=64)),
                ('path', models.CharField(help_text='文件相对路径', max_length=512)),
                ('size', models.BigIntegerField()),
            ],
            options={
                'verbose_name': '文件信息',
                'verbose_name_plural': '文件信息',
                'db_table': 'file_info',
            },
        ),
    ]
