# Generated by Django 4.2.15 on 2024-08-31 06:34

import common.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('deleted', models.BooleanField(default=False, help_text='是否删除')),
                ('name', models.CharField(blank=True, default='', help_text='难度程度名称', max_length=64, null=True)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, '简单'), (2, '一般'), (2, '困难')], default=1, help_text='等级')),
            ],
            options={
                'verbose_name': '计划困难等级表',
                'verbose_name_plural': '计划困难等级表',
                'db_table': 'plan_difficulty',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('deleted', models.BooleanField(default=False, help_text='是否删除')),
                ('name', models.CharField(blank=True, default='', help_text='计划名称', max_length=64, null=True)),
                ('start_time', models.DateTimeField(default=datetime.datetime.now, help_text='开始时间')),
                ('end_time', models.DateTimeField(default=datetime.datetime.now, help_text='结束时间')),
                ('level', common.fields.SimpleForeignKey(db_constraint=False, help_text='难度程度', on_delete=django.db.models.deletion.DO_NOTHING, related_name='plan_level', to='plan.planlevel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
