# Generated by Django 4.2.15 on 2024-09-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_alter_plan_options_alter_plan_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, '简单'), (2, '一般'), (2, '困难')], default=1, help_text='等级'),
        ),
        migrations.DeleteModel(
            name='PlanLevel',
        ),
    ]
