# Generated by Django 4.2.15 on 2024-09-01 18:28

import common.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
        ('plan', '0003_alter_plan_level_delete_planlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='user',
            field=common.fields.SimpleForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plan_user', to='auths.user'),
            preserve_default=False,
        ),
    ]
